# Generated by Django 4.2.3 on 2023-07-31 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candy',
            name='snack_on_the_go',
        ),
        migrations.RemoveField(
            model_name='snacks',
            name='snack_on_the_go',
        ),
        migrations.DeleteModel(
            name='SnackOnTheGo',
        ),
    ]
