# Generated by Django 4.2.3 on 2023-07-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_candy_snack_on_the_go_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Beverages',
            new_name='Beverage',
        ),
        migrations.RenameModel(
            old_name='FrozenItems',
            new_name='FrozenItem',
        ),
        migrations.RenameModel(
            old_name='Sundries',
            new_name='Sundrie',
        ),
        migrations.DeleteModel(
            name='Snacks',
        ),
    ]
